### PR TITLE
fix(halo-app): vault service worker

### LINKED ISSUE #2679: Create a notification from vault to parent about SW updates

### PR DESCRIPTION
**Pull request by wittjosiah**
- ensure fonts are cached by the service worker
- ensure vault is being cached for offline
- test and document service worker update paths, for vault and apps
- don't `fetch` vault for now as it breaks offline

Resolves #2679 

### Summary
🚀📄🐛

This pull request updates the service worker configuration and registration for the halo-app and composer-app packages, using the Vite plugin for PWA and service worker generation. It also adds documentation for the service worker behavior and best practices for the DXOS vault apps in the `REPOSITORY_GUIDE.md` file. These changes aim to improve the performance, reliability, and offline capabilities of the vault apps.

> _`vite.config.ts`_
> _Service workers cache wisely_
> _Winter web app_

### Walkthrough
*  Add and configure service workers for composer-app and halo-app using Vite plugin for PWA ([link](https://github.com/dxos/dxos/pull/3119/files?diff=unified&w=0#diff-813f00d5c5485f0f83ea1fb6782e90691a233ccb1d82f30a61d1a956f996082eL54-R55), [link](https://github.com/dxos/dxos/pull/3119/files?diff=unified&w=0#diff-a7514853e6e589e3fb4c59961a3097388c521aa62529e65f6574a56655a42d1cL6-R9), [link](https://github.com/dxos/dxos/pull/3119/files?diff=unified&w=0#diff-a7514853e6e589e3fb4c59961a3097388c521aa62529e65f6574a56655a42d1cR15-R38), [link](https://github.com/dxos/dxos/pull/3119/files?diff=unified&w=0#diff-a745999da1e2bed73f69f9a92baaad22d02ded554612912cb17f5727cfdb516eL61-R62))
*  Comment out fetch request and remove unused import in `iframe-service-proxy.ts` file for sdk/client package ([link](https://github.com/dxos/dxos/pull/3119/files?diff=unified&w=0#diff-834bad88edf4fe7524e1dec39240cfaea7edb5e085d465624fd568c2d42b859fL7-R7), [link](https://github.com/dxos/dxos/pull/3119/files?diff=unified&w=0#diff-834bad88edf4fe7524e1dec39240cfaea7edb5e085d465624fd568c2d42b859fL199-R205))
*  Add documentation for service worker behavior and configuration for DXOS vault apps in `REPOSITORY_GUIDE.md` file ([link](https://github.com/dxos/dxos/pull/3119/files?diff=unified&w=0#diff-fe358a8c0cd3d8f92b63c85fc3faea1a8536ff9ae395d45e49f01317fcb76c45L278-R298))

### CODE REVIEW

File: packages/sdk/client/src/packlets/client/iframe-service-proxy.ts [hunk 1]
```diff
@@ -196,10 +196,13 @@ export class IFrameClientServicesProxy implements ClientServicesProvider {
     );
 
     if (!this._iframe) {
-      const res = await fetch(source);
-      if (res.status >= 400) {
-        throw new RemoteServiceConnectionError(`Failed to fetch ${source}`, { source, status: res.status });
-      }
+      // TODO(wittjosiah): This doesn't work with generated service worker when offline. Remove?
+      //   Is there an easy way to respond to this without a lot of custom work inside the service worker?
+      //   Is getting an http response here helpful information or just overhead?
```
Comment (dmaretskyi) [inline packages/sdk/client/src/packlets/client/iframe-service-proxy.ts:201]: +1 for removing, if there's an http error when loading the iframe, you'll get a console message anyway

Comment (wittjosiah) [reply packages/sdk/client/src/packlets/client/iframe-service-proxy.ts:201]: I'm not sure you'd get a console message because it's not a fetch but just iframe being loaded. It's definitely visible in the network tools though.
