### PR TITLE
fix(plugin-registry): prevent plugins from jumping around when toggling enabled

### LINKED ISSUE #7415: [composer] toggling an experimental plugin off in the settings panel shouldn't cause it to disappear
currently toggling plugins on and off is quite jarring because of how they are sorted, toggling a plugin on or off shouldn't cause it disappear from the screen

### PR DESCRIPTION
**Pull request by wittjosiah**
Resolves #7415

### CODE REVIEW

File: packages/sdk/app-framework/src/plugins/PluginHost/PluginContext.tsx [hunk 1]
```diff
@@ -26,6 +26,7 @@ export type PluginContext = {
   /**
    * All available plugins.
    */
+  // This is metadata rather just ids because it includes plugins which have not been fully loaded yet.
```
Comment (ZaymonFC) [inline packages/sdk/app-framework/src/plugins/PluginHost/PluginContext.tsx:29]:
```suggestion
  // This is metadata rather then just ids because it includes plugins which have not been fully loaded yet.
```

**Review by ZaymonFC — APPROVED** [review]
Fun solution.

**Review by thure — APPROVED** [review]
swell ✨
