### PR TITLE
fix(authoring): Internal links work with deck

### LINKED ISSUE #7011: [authoring] internal links are broken
Links in a markdown document of the form:

```md
[A thing](/c49a27f8bbf524d10db1587e26985146daaa0eee4dad1ddbe267b200ba728192) is linked.
```

where `c49a27f8bbf524d10db1587e26985146daaa0eee4dad1ddbe267b200ba728192` is an object ID in ECHO.

They currently show an internal link icon: 

Image

But clicking the link doesn't navigate to the object.

### PR DESCRIPTION
**Pull request by ZaymonFC**
- Resolves #7011

As a follow up I'd like to simplify the active id manipulation that `SearchDialog` and `NavTreeContainer` by leveraging the new NavigationAction `ADD_TO_ACTIVE`.

Open to better names for the action, however, I'm not too fussed since they're ephemeral.

Clicking on an internal link multiple times in deck will only scroll and focus the linked object the first time. 
- More discussion here: #7197

### CODE REVIEW

File: packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx [hunk 1]
```diff
@@ -406,6 +406,56 @@ export const DeckPlugin = ({
...
+                      } else {
+                        main.push(id);
+                      }
+                    } else {
+                      const newIds = [id];
+                      const partMembers = new Set<string>();
+                      switch (settings.values.newPlankPositioning) {
+                        case 'start': {
+                          newIds.forEach((newId) => partMembers.add(newId));
+                          main.forEach((existingId) => partMembers.add(existingId));
```
Comment (thure) [inline packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx:430]: For this to work as expected, you have to filter `newIds` to just the ones not already in `main`, otherwise the ids move around. The implementation of `NavigationAction.OPEN` adjacent this one does that.

Comment (thure) [reply packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx:430]: I see this is an array with one item, and moving it is probably the point of this action, so never mind 😅

**Review by thure — APPROVED** [review]
Into it!
