### PR TITLE
fix(plugin-thread): Fix `autoFocus` on CM instances

### LINKED ISSUE #5711: [composer] chat steals focus
stand-alone chat (thread) autoFocus steals focus from any input that is showing in the main screen (e.g., "value" text input in Chain prompt). after every key press in text input, chat box autofocuses.

### PR DESCRIPTION
**Pull request by thure**
Resolves #5711 (again)

Care was taken to look at a variety of scenarios:
- ensure focus is not stolen when unwanted
- focus returns to the textbox after a message is sent
- focus moves to the textbox on mount when the user creates a new comment thread

https://github.com/dxos/dxos/assets/855039/a84e8d09-912a-4a7d-9b59-dde611b6ab01

https://github.com/dxos/dxos/assets/855039/aa75dbcb-926b-422d-a5c8-0045100f5dfa

Note that performance issues in the capture appear to be part of the automerge call stack

Screenshot 2024-02-20 at 18 49 32

### CODE REVIEW

File: packages/apps/plugins/plugin-thread/src/components/CommentContainer.tsx [hunk 1]
```diff
@@ -38,8 +38,14 @@ export const CommentContainer = ({
 
   const [nextMessage, setNextMessage] = useState({ text: new TextObject() });
   const nextMessageModel = useTextModel({ text: nextMessage.text, identity, space });
-  const autoFocusRef = useRef<boolean>(false);
-  autoFocusRef.current = !!autoFocus;
+  const [autoFocus, setAutoFocus] = useState(!!autoFocusTextbox);
+
+  // TODO(thure): Because of the way the `autoFocus` property is handled by TextEditor, this is the least-bad way of
+  //   moving focus at the right time, though it is an antipattern. Refactor to behave more like <input/>’s `autoFocus`
+  //   or `autofocus` (yes, they’re different).
```
Comment (wittjosiah) [inline packages/apps/plugins/plugin-thread/src/components/CommentContainer.tsx:45]: 😅

**Review by wittjosiah — APPROVED** [review]
