### PR TITLE
fix(plugin-help): Joyride interactivity

### LINKED ISSUE #5990: [composer] fix joyride for first time users

### PR DESCRIPTION
**Pull request by thure**
This PR:
- Resolves #5990
- Polishes the style, accessibility, keyboard access, and interactivity of the Joyride tooltip
- Adds accessors and listeners for shell display

https://github.com/dxos/dxos/assets/855039/c24d5e5b-6964-445b-9da9-cb70ac786999

### CODE REVIEW

**Review by ZaymonFC — APPROVED** [review]
Nice work. The shell changes look compatible and read-only so I'm not worried there.

File: packages/apps/composer-app/src/main.tsx [hunk 1]
```diff
@@ -139,11 +139,13 @@ const main = async () => {
       isDeck ? DeckMeta : LayoutMeta,
       NavTreeMeta,
       SettingsMeta,
-      HelpMeta,
       StatusBarMeta,
 
-      // Data integrations
+      // Shell and help
```
Comment (wittjosiah) [inline packages/apps/composer-app/src/main.tsx:144]: I'm not sure I understand the significance of this group

**Review by wittjosiah — APPROVED** [review]

File: packages/apps/composer-app/src/main.tsx (hunk 1 above)
Comment (thure) [reply packages/apps/composer-app/src/main.tsx:144]: Help now needs shell (so it knows when it’s open), but shell was part of the group below it and help is not a data persistence plugin… I’m amenable to other ideas if you have any.

Comment (wittjosiah) [reply packages/apps/composer-app/src/main.tsx:146]: does help need to come after client in order to get access to shell?

Comment (thure) [reply packages/apps/composer-app/src/main.tsx:146]: Yes exactly

Comment (wittjosiah) [reply packages/apps/composer-app/src/main.tsx:146]: why exactly? does help not render inside all of the contexts regardless?

Comment (thure) [reply packages/apps/composer-app/src/main.tsx:146]: In order to get the shell display status, it needs `client`, which it can only get beneath client’s context provider.

Comment (wittjosiah) [reply packages/apps/composer-app/src/main.tsx:146]: I see, help's logic is also in a context not in a component so the context order matters. We can fiddle with these later, this seem fine for now. Maybe just leave a clearer note stating that help needs to be after client for the context ordering.
