### PR TITLE
fix: Statusbar item popovers, other layout issues

### LINKED ISSUE #8609: [composer] Statusbar layout issues
There appear to be some issues with the statusbar elements and their popovers.

Image

### PR DESCRIPTION
**Pull request by thure**
This PR:
- resolves #8609.
- clears some other tech debt in the layout
- toggles nav sidebar from `lg` when clicking the active L0 tab

https://github.com/user-attachments/assets/874d6faa-4e70-41fb-b112-14df8bdf9c27

### CODE REVIEW

File: packages/plugins/plugin-navtree/src/components/L0Menu.tsx [hunk 1]
```diff
@@ -23,11 +24,30 @@ type L0ItemProps = {
...
+  const { tab, onTabChange, onSelect, isCurrent } = useNavTreeContext();
+  const { dispatchPromise: dispatch } = useIntentDispatcher();
+  const { navigationSidebarState } = useSidebars(NAVTREE_PLUGIN);
+  const [isLg] = useMediaQuery('lg', { ssr: false });
+
   return useCallback(
     (event: MouseEvent) => {
       switch (type) {
         case 'tab':
+          void dispatch(
```
Comment (wittjosiah) [inline packages/plugins/plugin-navtree/src/components/L0Menu.tsx:36]: I think this should maybe just be inside the onTabChange implementation?

**Review by wittjosiah — APPROVED** [review]
