### PR TITLE
fix(echo-schema): send updates for text objects

### LINKED ISSUE #3675: TextObject does not emit updates to subscribers
https://github.com/dxos/dxos/blob/main/packages/core/echo/echo-schema/src/text-object.ts#L76-L77

### LINKED ISSUE #4043: [composer] inferring document title from first line doesn't work until another doc is created
See video below, document titles are not inferred until another doc is created. The document title should be inferred from the first line as you type.

https://github.com/dxos/dxos/assets/3398896/f7619a2e-a196-49f3-86be-661ef2b2c266

### PR DESCRIPTION
**Pull request by wittjosiah**
Resolves #3675 
Resolves #4043

### Summary
🐛🚀🧪

This pull request fixes bugs in the `AppManager` class and the `Text` class that affected the playwright tests and the yjs updates for the composer app. It also adds logging functionality to the `Text` class and improves the test coverage for the multi-player and single-player scenarios.

> _`AppManager` fixed_
> _Playwright tests run smoothly_
> _Autumn bugs no more_

### Walkthrough
*  Fix bugs in the `AppManager` class methods that automate the playwright tests for the composer app by selecting the correct elements to click on ([link](https://github.com/dxos/dxos/pull/4120/files?diff=unified&w=0#diff-b295c0687b736b4159c9f82185a761df55201a2638d4a9ce708ca7b7b90b9b46L39-R39), [link](https://github.com/dxos/dxos/pull/4120/files?diff=unified&w=0#diff-b295c0687b736b4159c9f82185a761df55201a2638d4a9ce708ca7b7b90b9b46L45-R49), [link](https://github.com/dxos/dxos/pull/4120/files?diff=unified&w=0#diff-b295c0687b736b4159c9f82185a761df55201a2638d4a9ce708ca7b7b90b9b46L54-R55)).

### CODE REVIEW

File: packages/core/echo/echo-schema/src/text-object.ts [hunk 1]
```diff
@@ -71,14 +72,13 @@ export class Text extends EchoObject<TextModel> {
...
+    log('_afterBind', { id: this.id });
     this._model.initialize();
   }
 
   override _itemUpdate(): void {
-    // log.info('_itemUpdate', { id: this.id });
-    // TODO(wittjosiah): This stops yjs updates from working.
-    // super._itemUpdate();
+    log('_itemUpdate', { id: this.id });
+    super._itemUpdate();
```
Comment (wittjosiah) [inline packages/core/echo/echo-schema/src/text-object.ts:81]: Uncommenting this didn't seem to reintroduce the issues we were seeing before :shrug:
