### PR TITLE
fix: sketch serializer

### LINKED ISSUE #6749: [composer] drag-and-drop between spaces is broken for sketches
Steps to reproduce:

1. Create two spaces
2. Create a Sketch in the first
3. drag-and-drop the sketch into the second space

https://github.com/dxos/dxos/assets/1310143/38416b19-e531-4700-b098-37556ca89d4a

Console error:
```
react-D-u6Bfzb.js:32 Error: invariant violation [isReactiveObject(obj)] at packages/core/echo/echo-db/src/automerge/automerge-object.ts:16
```

### PR DESCRIPTION
**Pull request by wittjosiah**
During the clone operation only the sketch is serialized and the data isn't included.
Clone needs to not preserve ids right now so that you can copy things back and forth
between spaces and not have it fail because of id collision. Not preserving ids
makes references complicated because you need to update all the references.

The document serializer works because it collapses the references into a flat thing
(markdown) and then rebuilds the object structure afterwards. This does the same thing
but using json for sketch objects.

Resolves #6749

### CODE REVIEW

File: packages/apps/types/src/serializer/serializers/sketch.ts [hunk 1]
```diff
@@ -12,10 +14,41 @@ export const serializer: TypedObjectSerializer<SketchType> = {
   }),
 
   serialize: async ({ object }): Promise<string> => {
-    throw new Error('Not implemented.');
+    // TODO(wittjosiah): Implement `toJSON` method?
+    const sketch = { ...object, data: { ...object.data } };
```
Comment (yarolegovich) [inline packages/apps/types/src/serializer/serializers/sketch.ts:18]: I'd use `loadObjectReferences` on `object.data` first.
