### PR TITLE
fix(sketch): Decouple state across sketch instances

### LINKED ISSUE #7199: [sketch] Tldraw instances have coupled state
https://github.com/dxos/dxos/assets/12402727/37bd3bb1-25af-4c77-b97c-b334bec0ce8a

```[tasklist]
### Tasks
- [ ] Check that 'camera' positioning and zoom aren't coupled
- [ ] Check that pressing 'b', 'a', doesn't change selected tool for all visible instances
```

### LINKED ISSUE #7200: [sketch] Sketch plugin doesn't respect dark mode
image

### PR DESCRIPTION
**Pull request by ZaymonFC**
- Resolves #7199
- May also resolve #7200, can't repro now

### CODE REVIEW

File: packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx [hunk 1]
```diff
@@ -166,6 +167,7 @@ export const SketchPlugin = (): PluginDefinition<SketchPluginProvides> => {
               // NOTE: Min 500px height (for tools palette).
               return data.object instanceof DiagramType ? (
                 <SketchComponent
+                  key={fullyQualifiedId(data.object)} // Force instance per sketch object. Otherwise, sketch shares the same instance.
```
Comment (wittjosiah) [inline packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx:170]: is fully qualified id enough? there's no issue if the same sketch is on the screen twice?

Comment (ZaymonFC) [reply packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx:170]: Yeah it's working. Keyboard actions are still shared between instances of the *same* sketch, but it's kinda cool.

Comment (ZaymonFC) [reply packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx:170]: The background stuff was far more jarring.

**Review by wittjosiah — APPROVED** [review]
