### PR TITLE
fix(echo): automerge array element updates go through db backend

### LINKED ISSUE #5412: [echo] array object field updates are not reactive
A failing test patch:
```diff
diff --git a/packages/core/echo/echo-schema/src/object/subscription.test.ts b/packages/core/echo/echo-schema/src/object/subscription.test.ts
index 86960ff73..b523b18fe 100644
--- a/packages/core/echo/echo-schema/src/object/subscription.test.ts
+++ b/packages/core/echo/echo-schema/src/object/subscription.test.ts
@@ -98,6 +98,18 @@ describe('create subscription', () => {
   });
 });

+test('updates for automerge array object fields', async () => {
+  const { db } = await createDatabase();
+  const task = new Expando({ array: [{ title: 'Test value' }] }, { automerge: true });
+  db.add(task);
+
+  const counter = createUpdateCounter(task);
+
+  expect(counter.value).to.equal(1);
+  task.array[0].title = 'New value';
+  expect(counter.value).to.equal(2);
+});
+
 const createUpdateCounter = (object: any) => {
   const counter = { value: 0 };
   const selection = createSubscription(() => {
```

### PR DESCRIPTION
**Pull request by yarolegovich**
### Motivation / Background

Fixes #5412, related to #4882

### Details

* Fixed automerge array returning plain JS objects.
* Fixed root element fields potentially overriding property of nested objects. Schema got broken because `props` was now returning `AutomergeObject` instances with `id` field. And Proxy was routing `id` accesses to the root object.

### CODE REVIEW

File: packages/core/echo/echo-schema/src/automerge/automerge-object.ts [hunk 1]
```diff
@@ -134,7 +134,9 @@ export class AutomergeObject implements TypedObjectProperties {
     return this._id;
   }
 
-  [base] = this as any;
+  get [base]() {
```
Comment (yarolegovich) [inline packages/core/echo/echo-schema/src/automerge/automerge-object.ts:137]: Fixes test matcher. It's making a deep object copy, not copying symbols but setting a prototype making getters accessible.
