### PR TITLE
fix: Restore Thread-Sheet integration, fix Sheet model interactions

### LINKED ISSUE #7957: [sheet] Delete should clear the content of all cells within the selection

### LINKED ISSUE #7982: [sheet] Restore comments (as ranges)

### LINKED ISSUE #8024: [sheet] Model operations are buggy

### PR DESCRIPTION
**Pull request by thure**
This PR:
- resolves #7957
- resolves #8024
- resolves #7982

https://github.com/user-attachments/assets/150e3137-1f65-4785-8f82-93c1bc95e7db

https://github.com/user-attachments/assets/b2a5168a-7183-4a23-82cf-07c688a040b6

### CODE REVIEW

File: packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+      });
+
+      if (closestThread) {
+        void dispatch([
+          { action: 'dxos.org/plugin/thread/action/select', data: { current: fullyQualifiedId(closestThread) } },
+        ]);
+      }
+    },
+    [dispatch, threads],
+  );
```
Comment (ZaymonFC) [inline packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts:89]: We used to actively highlight in the sidebar whichever thread anchor was closest to the cursor, not just 1:1 overlap. This worked like the editor. Now we only select in the sidebar if we overlap?

**Review by ZaymonFC — APPROVED** [review]
The code looks solid.

File: packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts (hunk 1 above)
Comment (ZaymonFC) [reply packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts:89]: You could calculate distance to the range boundary fairly easily i'd say. It's a nice little sprinkle.

File: packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+          // TODO(Zan): Everywhere we refer to the cursor in a thread context should change to `anchor`.
+          const range = parseThreadAnchorAsCellRange(data.cursor);
+          range && grid.current?.setFocus({ ...range.to, plane: 'grid' }, true);
+        }
+      }
+    },
+    [model.sheet, setActiveRefs],
+  );
+
+  useIntentResolver(SHEET_PLUGIN, handleScrollIntoView);
```
Comment (richburdon) [inline packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts:52]: i think useIntentResolver should be removed since it obfuscates what's actually happening. i wrote this and it was intended to be short lived.

better to replace the callback above with:

```ts
  const { registerResolver } = useIntent();
  useEffect(() => {
    return registerResolver()
  }, []);
```

same pattern in the 3 other places.

File: packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts [hunk 3]
```diff
@@ -0,0 +1,101 @@
+//
+// Copyright 2024 DXOS.org
+//
+
+import { type MutableRefObject, useCallback, useEffect, useMemo } from 'react';
```
[the remark this answers is not in the document]
Comment (thure) [reply packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts:5]: I don’t prefer to have a hooks folder intentionally, see: https://discord.com/channels/837138313172353095/1110334757126017076/1299088207434219603

File: packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts (hunk 1 above)
Comment (thure) [reply packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts:89]: Agreed this is potentially a helpful increment, worth filing as an additional issue?

File: packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts (hunk 2 above)
Comment (thure) [reply packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts:52]: The scope of this PR might not be great for this refactor as I’m not familiar with this pattern and just moved it to a new file.

File: packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+
+import { useSheetContext } from '../components';
+import { type CellAddress, type CompleteCellRange, inRange } from '../defs';
+import { SHEET_PLUGIN } from '../meta';
+
+export const completeCellRangeToThreadCursor = (range: CompleteCellRange): string => {
+  return `${range.from.col},${range.from.row},${range.to.col},${range.to.row}`;
+};
+
+export const parseThreadAnchorAsCellRange = (cursor: string): CompleteCellRange | null => {
```
[the remark this answers is not in the document]
Comment (thure) [reply packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts:20]: I can’t find any logic in TablePlugin that deal with ranges — has this indeed been reimplemented somewhere?

File: packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts (hunk 2 above)
Comment (thure) [reply packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts:52]: I do think Sheet’s understanding of ranges (using `to` and `from`) are meaningfully distinct from `dx-grid`’s (using `start` and `end`), since either may or may not sort one coordinate relative to the other…
