### PR TITLE
fix: Polish items, link to Org table

### LINKED ISSUE #9123: Plank resize handle getting occluded by toolbars

### LINKED ISSUE #9124: Make related org of contact preview more generic & scalable

### LINKED ISSUE #9125: Message content not overflowing properly

### PR DESCRIPTION
**Pull request by thure**
This PR:
- resolves #9123
- resolves #9124
- resolves #9125

https://github.com/user-attachments/assets/178c8786-3b65-4932-8beb-ab957e8d69b9

Screenshot 2025-05-06 at 13 28 05
Screenshot 2025-05-06 at 13 16 38

### CODE REVIEW

File: packages/plugins/plugin-inbox/src/components/Message/Message.tsx [hunk 1]
```diff
@@ -61,10 +62,10 @@ export const Message = forwardRef<HTMLDivElement, MessageProps>(
...
     return (
-      <div role='none' className='grid grid-rows-[min-content_1fr] relative h-full overflow-hidden'>
+      <div role='none' className='grid grid-rows-[min-content_1fr]'>
         <MessageHeader ref={ref} message={message} viewMode={viewMode} onSenderClick={onSenderClick} />
-        <div role='none' className='overflow-y-auto h-full min-h-0 p-2'>
-          <div ref={parentRef} className={mx(classNames)} />
+        <div role='none' className='relative'>
+          <div role='none' ref={parentRef} className={mx('absolute inset-0', classNames)} />
         </div>
       </div>
```
Comment (ZaymonFC) [inline packages/plugins/plugin-inbox/src/components/Message/Message.tsx:70]: The secret 🛸. ✨

**Review by ZaymonFC — APPROVED** [review]
Thanks! This looks good to me.

File: packages/plugins/plugin-inbox/src/components/Message/Message.tsx (hunk 1 above)
Comment (thure) [reply packages/plugins/plugin-inbox/src/components/Message/Message.tsx:70]: I hate doing this, but I could find no other way to get grid to ignore CM’s intrinsic size…
