### PR TITLE
fix(react-ui-thread,plugin-thread): Polish layout & other styles

### LINKED ISSUE #5400: [comments] dark mode colors for commented ranges in editor
we need to fix the contrast here
Screenshot 2024-01-25 at 9 34 32 AM

### LINKED ISSUE #5423: [composer] RTE with tabster in TextEditor
Ref: https://github.com/dxos/dxos/pull/5424/files#diff-b00930ab8b3935dc62edbd2f9df9136934286d2c57d50d8c45f260a6fb3a84d5R90

```
VM122313 @fluentui_react-tabster.js:2443 Uncaught TypeError: Cannot read properties of undefined (reading 'relatedTarget')
    at HTMLDocument._onFocusIn (VM122313 @fluentui_react-tabster.js:2443:50)
    at HTMLDocument.focusInHandler (VM122389 keyborg.js:82:14)
    at HTMLDivElement.focus (VM122389 keyborg.js:91:22)
    at focusPreventScroll (VM122417 chunk-SQFLB3WZ.js:516:7)
    at VM122417 chunk-SQFLB3WZ.js:4035:34
    at DOMObserver.ignore (VM122417 chunk-SQFLB3WZ.js:6374:14)
    at handlers.mousedown (VM122417 chunk-SQFLB3WZ.js:4035:21)
    at InputState.runHandlers (VM122417 chunk-SQFLB3WZ.js:3676:13)
    at InputState.handleEvent (VM122417 chunk-SQFLB3WZ.js:3666:10)
_onFocusIn @ VM122313 @fluentui_react-tabster.js:2443
focusInHandler @ VM122389 keyborg.js:82
focus @ VM122389 keyborg.js:91
focusPreventScroll @ VM122417 chunk-SQFLB3WZ.js:516
(anonymous) @ VM122417 chunk-SQFLB3WZ.js:4035
ignore @ VM122417 chunk-SQFLB3WZ.js:6374
handlers.mousedown @ VM122417 chunk-SQFLB3WZ.js:4035
runHandlers @ VM122417 chunk-SQFLB3WZ.js:3676
handleEvent @ VM122417 chunk-SQFLB3WZ.js:3666
```

### LINKED ISSUE #5459: [comments] layout issues
- ~sidebar close button takes up whole header when search is disabled~ [see comment](https://github.com/dxos/dxos/issues/5459#issuecomment-1920086608)
- [x] scrollbar overlaps with thread content and delete button (leave padding to the right)
- [x] comment/message username should be less prominent that message content

---

- [x] leave overscroll space at bottom of thread so that bottom most comment isn't "glued" to bottom of screen
- [x] bottom of comment thread should scroll into view when comment selected in document
- [x] delete (x) button spans entire height of message

### LINKED ISSUE #5460: [comments] custom extension should be registered for previous message editors
- [x] style for custom prompt makes text too small

Image

### PR DESCRIPTION
**Pull request by thure**
This PR follows-up on #5392 to address outstanding issues. Resolves #5459. Resolves #5460. Resolves #5400. Resolves #5423.

https://github.com/dxos/dxos/assets/855039/ef2a4929-1340-45d7-bc76-5c3730a131a5

https://github.com/dxos/dxos/assets/855039/d0b77580-34ed-49e2-a791-6f5395ca9647

Screenshot 2024-01-31 at 17 16 13
Screenshot 2024-01-31 at 17 15 51
Screenshot 2024-01-31 at 14 44 33

https://github.com/dxos/dxos/assets/855039/2d269446-a272-4727-8fd1-4ed14f874d2d

Screenshot 2024-01-31 at 14 16 47

### CODE REVIEW

File: packages/apps/plugins/plugin-thread/src/components/ThreadContainer.tsx [hunk 1]
```diff
@@ -97,7 +98,7 @@ export const ThreadContainer = ({
   const textboxMetadata = useMessageMetadata(thread.id, identity);
 
   return (
-    <Thread onClickCapture={onAttend} onFocusCapture={onAttend} current={current}>
+    <Thread onClickCapture={onAttend} onFocusCapture={onAttend} current={current} id={thread.id}>
```
Comment (richburdon) [inline packages/apps/plugins/plugin-thread/src/components/ThreadContainer.tsx:101]: prefer our props up-front (esp. id) and callbacks at the end semi-standard.

**Review by richburdon — APPROVED** [review]
nice!

File: packages/apps/plugins/plugin-thread/src/components/ThreadContainer.tsx (hunk 1 above)
Comment (thure) [reply packages/apps/plugins/plugin-thread/src/components/ThreadContainer.tsx:101]: Will keep that in mind 👍
