### PR TITLE
fix(composer): Anchor settings dialog to prevent content jumps

### LINKED ISSUE #6488: [composer] settings should anchor to viewport to prevent bouncing when switching between panels

### PR DESCRIPTION
**Pull request by ZaymonFC**
Pretty simple fix since we were able to leverage the work done for #6145

- Resolves #6488

https://github.com/dxos/dxos/assets/12402727/6c501fc4-60b6-4237-8383-0e9d8454aff7

### CODE REVIEW

File: packages/apps/plugins/plugin-settings/src/components/SettingsDialog.tsx [hunk 1]
```diff
@@ -35,7 +35,7 @@ export const SettingsDialog = ({
     .sort(({ name: a }, { name: b }) => a?.localeCompare(b ?? '') ?? 0);
 
   return (
-    <Dialog.Content classNames={['h-full md:max-is-[40rem] overflow-hidden']}>
+    <Dialog.Content classNames={['h-auto h-max-full md:max-is-[40rem] overflow-hidden']}>
```
Comment (thure) [inline packages/apps/plugins/plugin-settings/src/components/SettingsDialog.tsx:38]:
```suggestion
    <Dialog.Content classNames={['bs-content max-bs-full md:max-is-[40rem] overflow-hidden']}>
```
Whether this will limit its size depends on the layout (I’m forgetting), a `max-bs` rule might be unnecessary or have no effect.

**Review by thure — APPROVED** [review]
lgtm! just a couple nits to consider
