### PR TITLE
fix(plugin-navtree): Restore rearrange spaces

### LINKED ISSUE #8741: DnD to rearrange spaces in L0

### PR DESCRIPTION
**Pull request by thure**
This PR:
- resolves #8741.

https://github.com/user-attachments/assets/42bcc680-dc2f-446f-86ab-3620672ee2c1

### CODE REVIEW

File: packages/ui/react-ui-stack/src/components/StackContext.tsx [hunk 1]
```diff
@@ -13,9 +13,9 @@ export type StackItemSize = DndSize;
 
 export type StackItemData = { id: string; type: 'column' | 'card' };
 
-export type StackItemRearrangeHandler = (
-  source: StackItemData,
-  target: StackItemData,
+export type StackItemRearrangeHandler<D extends { id: string } = StackItemData> = (
+  source: D,
+  target: D,
```
Comment (wittjosiah) [inline packages/ui/react-ui-stack/src/components/StackContext.tsx:18]:
```suggestion
export type StackItemRearrangeHandler<Data extends { id: string } = StackItemData> = (
  source: Data,
  target: Data,
```

imo no reason type generics need to be a single letter if it helps explain what the generic is

**Review by wittjosiah — APPROVED** [review]
